### ISSUE TITLE
can't save files from other apps

### ISSUE THREAD

**Issue by userj** [ubports/filemanager-app#25] opened 2017-12-13 03:57 UTC
Ubports devel channel
Devices; Bacon

File Manager (Dev Branch)
Unable to save file downloads from telegram or Dekko

**Comment by NeoTheThird** [comment] 2017-12-13 13:57
@sverzegnassi How do you want to handle reports for the dev branch?

**Comment by sverzegnassi** [comment] 2017-12-13 16:13
Thanks @userj for reporting this.

The issue has been already fixed on GitHub, but we still need some time before releasing a new update on OpenStore. We've been fixing a few issues with the Samba support, but we haven't completed the work yet. Hopefully, I'll find some time during this week :)

@NeoTheThird , I specified in the app description on OpenStore to use the bug tracker at https://github.com/sverzegnassi/filemanager-app/issues

Not a problem though, the issue has been already addressed. I'd suggest to keep this report opened, and close it in the following days as the new release lands on OpenStore.

**Comment by NeoTheThird** [comment] 2017-12-13 16:53
Ok. What's the roadmap with the dev-branch? By when is it supposed to replace this one?

**Comment by sverzegnassi** [comment] 2017-12-13 17:00
There's still some minor adjustment we need to do, however we haven't received many complaints about broken functionalities. So I presume it's already good enough for replacing the old FM.

I should be able to finish it within the end of the year (which means before 28th, as I'll be afk and won't be able to do anything). My hope is to make it in time for OTA-3.

**Comment by nfsprodriver** [comment] 2018-10-28 18:33
Duplicate of #48 , fixed.

**Closed by nfsprodriver** 2018-10-28 18:33 UTC

**Comment by mihaelmilea** [comment] 2019-01-04 09:45
@sverzegnassi I was going to report this when I saw this thread with the fix and explanations. Until it is released to OpenStore, where can I get the new version? Thank you for the fix and for all the work!!! :)
